### ISSUE TITLE
[Feat] 돈 줍기 좌표 전송 및 로직 작성

### ISSUE THREAD

**Issue by Kguswo** [Kguswo/OMG#119]
## Issue
- (가정 1) 주울 돈 좌표 일단 10개 선정 (1~10)
- (가정 2) 맵에 랜덤 5곳에 돈 생성
- (가정 3) 가까이 갔을 때 스페이스바로 이 로직이 실행될것임

- 랜덤돈 배열 [좌표1, 좌표2, 좌표3, 좌표4, 좌표5] , 먹었는지 여부 및 얼마 짜린지(0, 1, 2) [0, 1, 0, 2, 1] 이런식, 0: 먹었음, 1: 안먹은 돈(싼거), 2: 안먹은 돈(비싼거)
- 먹었을 때 request로 roomId, playerNickname, 좌표 K 이렇게 받으면 -> 해당 좌표 먹었음을 처리 + 배열을 응답으로 , 그리고 해당 유저 돈 증가시키고 새로운 해당유저 개인판을 응답으로 (총 응답 2개 즉시 전송됨)
- 저 돈 좌표배열은 메인판과 같은 시기에 주기적으로 전송시킬 것. 개인판은 특정 플레이어가 먹었을 때 추가로 전송 (거래행위처럼)

## Todo
- [ ] 랜덤 돈 생성
- [ ] 먹은 돈 처리 및 응답
- [ ] 개인판 수정 및 응답
- [ ] API 명세서 작성

*Migrated from GitLab: https://lab.ssafy.com/s11-fintech-finance-sub1/S11P21A206/-/issues/119*

**Comment by Kguswo** [comment]
mentioned in commit 597af87a220d825f1d1ca5e1b91c59fa6a2195cd

**Comment by Kguswo** [comment]
mentioned in commit cf0501ce7ea17e46fd687fffde1c07252b91cb52

**Comment by Kguswo** [comment]
mentioned in commit c09e1e0ef67630b8d9d3fe3e5a0f43b33c4c0ec0

**Comment by Kguswo** [comment]
mentioned in commit 3e49ca3077c020d694eeda7a8895c70ffcf85291

**Comment by Kguswo** [comment]
In GitLab by @ssenna3 on Oct 14, 2024, 21:50 GMT+9

mentioned in commit e234c3a7f0e01ca41a1f5e35821fafe48dff5af4
