### ISSUE TITLE
[Feat] MainMap 렌더링 - 3D 크리스마스 배경에 캐릭터 애니메이션 적용

### ISSUE THREAD

**Issue by Kguswo** [Kguswo/OMG#12]
In GitLab by @hi-react on Sep 20, 2024, 12:24 GMT+9

## Issue
- @types/three 라이브러리 추가
- 미키 캐릭터에 애니메이션 동작 추가 (대기 / 걷기 / 왼쪽 돌기 / 오른쪽 돌기 / 줍기)
- 방향키 이용해 애니메이션 연동
- 임시 sketchfab 3D 배경에 미키 캐릭터 띄우기

## ToDo List
- [x] 컨셉 및 에셋 확정
- [x] 3D 맵 내에서 캐릭터 움직이도록 하기
- [x] 좌표 및 방향 처리
- [x] 위쪽 방향키 3초 이상 누르면 달리기 애니메이션으로 전환하기

*Migrated from GitLab: https://lab.ssafy.com/s11-fintech-finance-sub1/S11P21A206/-/issues/12*

**Comment by Kguswo** [comment]
In GitLab by @hi-react on Sep 20, 2024, 12:49 GMT+9

mentioned in commit cef7ed32182af24a878b734e39d6c97a45b78afe

**Comment by Kguswo** [comment]
In GitLab by @hi-react on Sep 20, 2024, 12:51 GMT+9

mentioned in commit 8d746f88bb979ffcc62353bb54d74f42a3b55669

**Comment by Kguswo** [comment]
In GitLab by @hi-react on Sep 20, 2024, 16:44 GMT+9

mentioned in commit 0d68f37d74ac9e79fab6ca16295ddd93c692281d

**Comment by Kguswo** [comment]
In GitLab by @hi-react on Sep 23, 2024, 22:13 GMT+9

marked the checklist item **컨셉 및 에셋 확정** as completed

**Comment by Kguswo** [comment]
In GitLab by @hi-react on Sep 24, 2024, 17:12 GMT+9

mentioned in commit ebc2faba6e8843a8653776bb66b717ae88aa43e7

**Comment by Kguswo** [comment]
In GitLab by @hi-react on Sep 24, 2024, 17:17 GMT+9

mentioned in commit d953407a2a7d57d214040b298253348ae25f1e99

**Comment by Kguswo** [comment]
In GitLab by @hi-react on Sep 25, 2024, 13:27 GMT+9

mentioned in commit 628ef21ee38f3e9370bedcc6b1419adc83ac446f

**Comment by Kguswo** [comment]
In GitLab by @hi-react on Sep 25, 2024, 13:27 GMT+9

mentioned in commit f6e7e933bcbe56adc995759b29e4e37e2c98a38c

**Comment by Kguswo** [comment]
In GitLab by @hi-react on Sep 26, 2024, 10:57 GMT+9

marked the checklist item **3D 맵 내에서 캐릭터 움직이도록 하기** as completed

**Comment by Kguswo** [comment]
In GitLab by @hi-react on Sep 26, 2024, 10:57 GMT+9

marked the checklist item **위쪽 방향키 3초 이상 누르면 달리기 애니메이션으로 전환하기** as completed

**Comment by Kguswo** [comment]
In GitLab by @hi-react on Sep 26, 2024, 10:57 GMT+9

marked the checklist item **좌표 및 방향 처리** as completed
