### ISSUE TITLE
[Feat] 게임 진행 : 게임 라운드 및 이벤트 적용 타이머 구현

### ISSUE THREAD

**Issue by Kguswo** [Kguswo/OMG#17]
## Issue
- 게임 내 타이머 적용 부분 및 시간을 멈춰야 할 이벤트에 대한 타이머 구현

## ToDo List
- [x] 플레이어별 행동 시간은 삭제하고 동시에 진행.
- [x] 각 라운드마다 고정된 120초 적용.
- [x] 각 라운드 내부에서 경제 이벤트, 주가 변동이 일어났을 때 즉시 일시적인 시간만큼 타이머를 정지
- [x] 주가 수준 변경은 주가 변동에 의해서만 일어나기 때문에 주가 수준 변경까지 일어난다면 이 이벤트까지 모두 끝이났을 때 타이머 재개

*Migrated from GitLab: https://lab.ssafy.com/s11-fintech-finance-sub1/S11P21A206/-/issues/17*

**Comment by Kguswo** [comment]
mentioned in commit 644724c1234bd47f2c650e267f1d40b0e55755c5

**Comment by Kguswo** [comment]
mentioned in commit b77b3763e6f15c17cf7bfec03daa8ffd5ca7eec8

**Comment by Kguswo** [comment]
mentioned in commit 07ec08abcee068cab0fa4c00327bc116e675290c

**Comment by Kguswo** [comment]
mentioned in commit 3559a54a5544ce958cea04865ead739e22966e09

**Comment by Kguswo** [comment]
mentioned in commit 2336d5a269c4d7237954a7cdcaabaac519a86aca

**Comment by Kguswo** [comment]
mentioned in commit c89e5f2a48321e13597abe8dddf421eb712b4d77

**Comment by Kguswo** [comment]
mentioned in commit 626d2fa1b1e1ac6a07c53f83936464994d4d844e

**Comment by Kguswo** [comment]
mentioned in commit a2f777eec3988740e5862767a36f06cb82b79afa

**Comment by Kguswo** [comment]
mentioned in commit 30adefa906869a2c2d7dac21ec8c4bc5d32edabe

**Comment by Kguswo** [comment]
marked the checklist item **각 라운드마다 고정된 120초 적용.** as completed

**Comment by Kguswo** [comment]
marked the checklist item **각 라운드 내부에서 경제 이벤트, 주가 변동이 일어났을 때 즉시 일시적인 시간만큼 타이머를 정지** as completed

**Comment by Kguswo** [comment]
marked the checklist item **주가 수준 변경은 주가 변동에 의해서만 일어나기 때문에 주가 수준 변경까지 일어난다면 이 이벤트까지 모두 끝이났을 때 타이머 재개** as completed

**Comment by Kguswo** [comment]
marked the checklist item **주가 수준 변경은 주가 변동에 의해서만 일어나기 때문에 주가 수준 변경까지 일어난다면 이 이벤트까지 모두 끝이났을 때 타이머 재개** as incomplete

**Comment by Kguswo** [comment]
marked the checklist item **주가 수준 변경은 주가 변동에 의해서만 일어나기 때문에 주가 수준 변경까지 일어난다면 이 이벤트까지 모두 끝이났을 때 타이머 재개** as completed

**Comment by Kguswo** [comment]
mentioned in commit b9f23e00a3ce6a0c7340006aadf578973d8b2d84
