### ISSUE TITLE
[Feat] 게임 내부 로직 개발 - 주식 매도

### ISSUE THREAD

**Issue by Kguswo** [Kguswo/OMG#18]
In GitLab by @Celinemad on Sep 23, 2024, 17:55 GMT+9

## Issue

* 게임 내부 로직 개발 - 주식 매도

## ToDo List

* [x] 1\. 주식 매도 처리
* [x] 2\. 매도 트랙에 주식 토큰 놓기
* [x] 3\. 주가 하락
* [x] 4\. 주가변동 
* [x] 5\. 주식 매도트랙 세팅

*Migrated from GitLab: https://lab.ssafy.com/s11-fintech-finance-sub1/S11P21A206/-/issues/18*

**Comment by Kguswo** [comment]
In GitLab by @Celinemad on Sep 24, 2024, 15:51 GMT+9

marked the checklist item **Controller(/game.sellStock)** as completed

**Comment by Kguswo** [comment]
In GitLab by @Celinemad on Sep 24, 2024, 15:51 GMT+9

marked the checklist item **Service** as completed

**Comment by Kguswo** [comment]
In GitLab by @Celinemad on Sep 25, 2024, 15:03 GMT+9

mentioned in commit 4d9bab325b9c4b23c774805edfb0f2c852737530

**Comment by Kguswo** [comment]
In GitLab by @Celinemad on Sep 25, 2024, 15:03 GMT+9

mentioned in commit 279754984db07f6fd66279eb0bf641ebaef9b70d

**Comment by Kguswo** [comment]
In GitLab by @Celinemad on Sep 25, 2024, 15:03 GMT+9

mentioned in commit 89939d5fd2268577ab331929899fc449dfa4f7c6

**Comment by Kguswo** [comment]
In GitLab by @Celinemad on Sep 26, 2024, 08:24 GMT+9

mentioned in commit 5d4e35060200b760bc63f2251b9b12305803aa8d

**Comment by Kguswo** [comment]
In GitLab by @Celinemad on Sep 26, 2024, 08:24 GMT+9

mentioned in commit a0906d5b26fdba0724b769cdeab43114555cbd50

**Comment by Kguswo** [comment]
In GitLab by @Celinemad on Sep 26, 2024, 17:55 GMT+9

mentioned in commit 491dbd37f22cb57b30fd387ad7017d41b8c84359

**Comment by Kguswo** [comment]
In GitLab by @Celinemad on Sep 27, 2024, 15:13 GMT+9

mentioned in commit beae588d877a027cdafe915995db94d342809b6d

**Comment by Kguswo** [comment]
In GitLab by @Celinemad on Sep 27, 2024, 15:13 GMT+9

mentioned in commit 1940f56337639f173244d52a938f265680a8af74

**Comment by Kguswo** [comment]
In GitLab by @Celinemad on Sep 27, 2024, 15:13 GMT+9

mentioned in commit 1d21236dc80f92f70b6910b4892d1d7ed577b9dc
