### ISSUE TITLE
[Feat#30] 금괴 매입 - [merged]

### ISSUE THREAD

**Issue by Kguswo** [Kguswo/OMG#181]
_Merges feature/back/game-gold -> develop_

## Issue
- 게임 진행 로직 중 금괴 매입과 관련된 파일을 작성합니다
- 주가거래소에 도착 후 금괴 매입 진행 시 일어나는 변동 사항 구현
- 아직 거래소와 캐릭터가 상호작용하는 부분까지 완벽적용 하지 않았습니다.
- 그 외 테스트 완료했습니다.
- 타이머 로직을 수정했습니다. 타이머 ROUND START전 TUTORIAL 상태를 추가하여 20초동안 튜토리얼 진행 후 1라운드가 시작됩니다.

## ToDo List
- [x] 플레이어가 거래소에 접근 해 필수 행동을 진행 한다는 조건을 만족 시 진행 가능
- [x] 플레이어가 금괴 매입 시 해당 주가 수준에서 매입 가능한 금괴 개수 이하를 매입 가능, 초과 선택 시 예외 response
- [x] 초과 선택이 불가능하도록 예외시 alert 발생할 수 있는 조건 체크
- [x] 플레이어는 보유한 자산에서 매입 가능한 최대 금괴 이하의 개수만 매입 가능
- [x] 게임 초기화 시 20초 튜토리얼 적용 

그 외 추가할 사항이나 궁금한 점 comment 남겨주세요

closes #30

*Migrated from GitLab: https://lab.ssafy.com/s11-fintech-finance-sub1/S11P21A206/-/merge_requests/50*

**Comment by Kguswo** [comment]
requested review from @ssenna3

**Comment by Kguswo** [comment]
@ssenna3 타이머 로직 수정완료했습니다. develop 브랜치 pull 받아 테스트 가능합니다.
추가로 금괴 API명세 노션에 작성중입니다.

에셋과 거래소 상호작용 관련은 추가 논의 후 추가 해야 할 것 같습니다.
주가 변동 메서드도 작성되면 추가해야합니다.

노션에 API 명세 추가했습니다

**Comment by Kguswo** [comment]
approved this merge request

**Comment by Kguswo** [comment]
mentioned in commit 309995cb91de2e1907b493a7716e6f90adf11681
