### ISSUE TITLE
[Feat] 금괴 매입

### ISSUE THREAD

**Issue by Kguswo** [Kguswo/OMG#30]
## Issue
- 게임 진행 로직 중 금괴 매입과 관련된 파일을 작성합니다
- 주가거래소에 도착 후 금괴 매입 진행 시 일어나는 변동 사항 구현

## ToDo List
- [x] 플레이어가 거래소에 접근 해 필수 행동을 진행 한다는 조건을 만족 시 진행 가능
- [x] 플레이어가 금괴 매입 시 해당 주가 수준에서 매입 가능한 금괴 개수 이하를 매입 가능, 초과 선택 시 예외 response
- [x] 초과 선택이 불가능하도록 예외시 alert 발생할 수 있는 조건 체크
- [x] 플레이어는 보유한 자산에서 매입 가능한 최대 금괴 이하의 개수만 매입 가능

*Migrated from GitLab: https://lab.ssafy.com/s11-fintech-finance-sub1/S11P21A206/-/issues/30*

**Comment by Kguswo** [comment]
marked the checklist item **플레이어가 거래소에 접근 해 필수 행동을 진행 한다는 조건을 만족 시 진행 가능** as completed

**Comment by Kguswo** [comment]
marked the checklist item **플레이어가 금괴 매입 시 해당 주가 수준에서 매입 가능한 금괴 개수 이하를 매입 가능, 초과 선택 시 예외 response** as completed

**Comment by Kguswo** [comment]
marked the checklist item **초과 선택이 불가능하도록 예외시 alert 발생할 수 있는 조건 체크** as completed

**Comment by Kguswo** [comment]
marked the checklist item **플레이어는 보유한 자산에서 매입 가능한 최대 금괴 이하의 개수만 매입 가능** as completed

**Comment by Kguswo** [comment]
mentioned in commit b5f7eae5771063079ef2864aad2ec886e4072187

**Comment by Kguswo** [comment]
mentioned in commit 5b414210aa1cd1aa82093827ce8436dab6c2b414

**Comment by Kguswo** [comment]
mentioned in commit 0ce513a5af3bd557e384c64928f7a7ac83a6a4fb

**Comment by Kguswo** [comment]
mentioned in commit e0d4e88b25f9bdadc07fb568dfafb5a29298ecd8

**Comment by Kguswo** [comment]
mentioned in commit 3fc466694b55daa47f155429219f2403447f7a18

**Comment by Kguswo** [comment]
mentioned in commit 0fdbb1e671f91f77fa42d9ff28d9549526ef26ea

**Comment by Kguswo** [comment]
mentioned in commit fbd6a59d945bc06e24c95072cd72b01c2395ed50

**Comment by Kguswo** [comment]
mentioned in commit 06d43c693c4cb03dac2a16c632d08233aab21f1e

**Comment by Kguswo** [comment]
mentioned in commit b68e34622b3fda696cb1f65c94ee62ed78716cf5

**Comment by Kguswo** [comment]
mentioned in commit fb4dc46703dce7bc6b76a13024d416587d7e74a2

**Comment by Kguswo** [comment]
mentioned in commit d9efad2b90c5d7073fdd04064228f3495f215596

**Comment by Kguswo** [comment]
mentioned in commit 309995cb91de2e1907b493a7716e6f90adf11681

**Comment by Kguswo** [comment]
mentioned in commit 04d21bb30a29f0493aac7d0df5eec6d511bcd281

**Comment by Kguswo** [comment]
mentioned in commit 10fe32522729363927dd452e01964b88a5d7501c

**Comment by Kguswo** [comment]
mentioned in commit d88d2862424dde0d5e8feaa69d66e06e93fa6af4

**Comment by Kguswo** [comment]
mentioned in commit 19221a4fcac157e9e609a5043e90e1c656e58370

**Comment by Kguswo** [comment]
mentioned in commit 797ce164b2bfeefeb1d82c7d2507f152969ede47

**Comment by Kguswo** [comment]
mentioned in commit a2649194ede6adf81d594492c550e17c244be988

**Comment by Kguswo** [comment]
mentioned in commit 6d8f7eeb8bac4dccde7d4b457e47abe235bba303

**Comment by Kguswo** [comment]
mentioned in commit a537050de9fa1909e46c4a0d0ae20b93ba9d36df

**Comment by Kguswo** [comment]
mentioned in commit 4e8e7a47d40d7df833ee28e710ff3a20bb07f896
