### ISSUE TITLE
[Feat] 주식 시장 컴포넌트 처리

### ISSUE THREAD

**Issue by Kguswo** [Kguswo/OMG#34]
In GitLab by @hi-react on Sep 27, 2024, 13:06 GMT+9

## Issue
- 주식 시장 마켓 배경 이미지 & 눈 내리는 효과 적용
- 3D 에셋 렌더링 및 애니메이션 적용 (트리 및 트리 장식 5개)
  - socks-in-cane
  - cane
  - socks
  - reels
  - candy
- 트리 장식 클릭 시, 임의의 바구니 구역 내에 선택한 장식 넣어주기
- 바구니에 있는 트리 장식 클릭 시, 선택 취소
- 예외 처리
  - 보유 현금 초과 시 alert
  - 최대 거래 수량 초과 시 alert

## ToDo List
- [x] 백엔드와 서버 통신 (구매 요청 보내기)
- [x] 갱신된 데이터로 수정해주기
- [x] 기타 UI 작업 고민 및 업데이트

*Migrated from GitLab: https://lab.ssafy.com/s11-fintech-finance-sub1/S11P21A206/-/issues/34*

**Comment by Kguswo** [comment]
In GitLab by @hi-react on Sep 27, 2024, 13:13 GMT+9

mentioned in commit c8bdeb50251349628dd270ea03dc646993b43664

**Comment by Kguswo** [comment]
In GitLab by @hi-react on Sep 27, 2024, 13:14 GMT+9

mentioned in commit 49b96153f70546c3ae56fc8de5ab1ac2487a6530

**Comment by Kguswo** [comment]
In GitLab by @hi-react on Sep 30, 2024, 08:46 GMT+9

mentioned in commit d542b78044fec7dfa530991b991b1b058514c7bd

**Comment by Kguswo** [comment]
In GitLab by @hi-react on Sep 30, 2024, 08:46 GMT+9

mentioned in commit 545f75226c4f4e808726b2f0278281d15a21839b

**Comment by Kguswo** [comment]
In GitLab by @hi-react on Sep 30, 2024, 21:56 GMT+9

mentioned in commit 12c53f670a4c203c38f3498625c408ae83ffff6c

**Comment by Kguswo** [comment]
In GitLab by @hi-react on Sep 30, 2024, 21:56 GMT+9

mentioned in commit 042cfcb9d348ca8ace6c3d0dad0259beec573d06

**Comment by Kguswo** [comment]
In GitLab by @hi-react on Sep 30, 2024, 21:57 GMT+9

mentioned in commit 3b847c5f3a4c6ce1e7b30104c142344f1c8f0111

**Comment by Kguswo** [comment]
In GitLab by @hi-react on Oct 1, 2024, 09:01 GMT+9

mentioned in commit e0d79f06bdf99a71393ae2768d650b1ae4917e83

**Comment by Kguswo** [comment]
In GitLab by @hi-react on Oct 2, 2024, 08:37 GMT+9

mentioned in commit abc359be9bac0eb67f614af3b6f131d78d4d6540

**Comment by Kguswo** [comment]
In GitLab by @hi-react on Oct 2, 2024, 08:37 GMT+9

mentioned in commit 58c567ab65e23f2ad07335089dac9c22b60ba924

**Comment by Kguswo** [comment]
In GitLab by @hi-react on Oct 2, 2024, 08:37 GMT+9

mentioned in commit 3728ce4960df28c0328a7a7b70b5cb8698146a08

**Comment by Kguswo** [comment]
In GitLab by @hi-react on Oct 2, 2024, 08:40 GMT+9

mentioned in commit c2e679007fbdbac51f694cf97983cbd9d94f8549

**Comment by Kguswo** [comment]
In GitLab by @hi-react on Oct 3, 2024, 11:15 GMT+9

mentioned in commit 5dda17b3d047e6e05e52c1998bf048e5f1cc30d0

**Comment by Kguswo** [comment]
In GitLab by @hi-react on Oct 3, 2024, 11:15 GMT+9

mentioned in commit 6ad2f5da227e10d5e4634904f50664a4160a716f

**Comment by Kguswo** [comment]
In GitLab by @hi-react on Oct 3, 2024, 12:54 GMT+9

mentioned in commit 0a75e25fa80fee9b90ab90acfa9b7e9fb06e6b8c

**Comment by Kguswo** [comment]
In GitLab by @hi-react on Oct 10, 2024, 14:19 GMT+9

marked the checklist item **백엔드와 서버 통신 (구매 요청 보내기)** as completed

**Comment by Kguswo** [comment]
In GitLab by @hi-react on Oct 10, 2024, 14:19 GMT+9

marked the checklist item **백엔드와 서버 통신 (구매 요청 보내기)** as incomplete

**Comment by Kguswo** [comment]
In GitLab by @hi-react on Oct 10, 2024, 14:19 GMT+9

marked the checklist item **백엔드와 서버 통신 (구매 요청 보내기)** as completed

**Comment by Kguswo** [comment]
In GitLab by @hi-react on Oct 10, 2024, 14:19 GMT+9

marked the checklist item **갱신된 데이터로 수정해주기** as completed

**Comment by Kguswo** [comment]
In GitLab by @hi-react on Oct 10, 2024, 14:19 GMT+9

marked the checklist item **기타 UI 작업 고민 및 업데이트** as completed
