### ISSUE TITLE
[Fix] 대출 수정, 주식 거래소 정보 전송

### ISSUE THREAD

**Issue by Kguswo** [Kguswo/OMG#35]
In GitLab by @Celinemad on Sep 27, 2024, 16:00 GMT+9

## Issue

* GameController =\> test용 || IndividualMessageController =\> 게임 로직 메세지 매핑용

## ToDo List

* [x] 대출, 상환, 주식 매도 MessageMapping으로 변경
* [x] 따발총 호출 예외 추가하기 (BaseResponse에 있음)

#### \[대출\]

* [x] 대출 변동사항 수정

#### \[주식 거래\]

* [x] 주식 거래소 메세지 전송

*Migrated from GitLab: https://lab.ssafy.com/s11-fintech-finance-sub1/S11P21A206/-/issues/35*

**Comment by Kguswo** [comment]
In GitLab by @Celinemad on Sep 28, 2024, 18:05 GMT+9

mentioned in commit 7fb567cde95931946c882715e4190d593942737c

**Comment by Kguswo** [comment]
In GitLab by @Celinemad on Sep 29, 2024, 17:10 GMT+9

mentioned in commit a11f9743ef91c31a91175e53ca9e09c2eef85516

**Comment by Kguswo** [comment]
In GitLab by @Celinemad on Sep 29, 2024, 17:55 GMT+9

mentioned in commit 7fc25da905834dbe5f5372190e5bde2d6afa17aa

**Comment by Kguswo** [comment]
In GitLab by @Celinemad on Sep 29, 2024, 19:38 GMT+9

mentioned in commit b65ecae09c8ff475a3128e92772ebf8824f86a14

**Comment by Kguswo** [comment]
In GitLab by @Celinemad on Sep 29, 2024, 22:27 GMT+9

mentioned in commit 7ea65d62d6ebe6c6b9ff85adc242d5cf4412a2f6

**Comment by Kguswo** [comment]
In GitLab by @Celinemad on Sep 30, 2024, 08:51 GMT+9

marked the checklist item **대출, 상환, 주식 매도 MessageMapping으로 변경** as completed

**Comment by Kguswo** [comment]
In GitLab by @Celinemad on Sep 30, 2024, 08:51 GMT+9

marked the checklist item **따발총 호출 예외 추가하기 (BaseResponse에 있음)** as completed

**Comment by Kguswo** [comment]
In GitLab by @Celinemad on Sep 30, 2024, 21:53 GMT+9

mentioned in commit ebb41b5b3bf60cf3f81452058c6f565798aac685

**Comment by Kguswo** [comment]
In GitLab by @Celinemad on Sep 30, 2024, 21:53 GMT+9

mentioned in commit 908f42c729d20473c0a25d38a7e86245abc03b98

**Comment by Kguswo** [comment]
In GitLab by @Celinemad on Oct 1, 2024, 18:45 GMT+9

mentioned in commit a0c2a8aeb3a0b73e727228fa533255086e612d8d

**Comment by Kguswo** [comment]
In GitLab by @Celinemad on Oct 1, 2024, 18:45 GMT+9

mentioned in commit 000dce96847f6bf9444927b3153e69d92a682eff

**Comment by Kguswo** [comment]
In GitLab by @Celinemad on Oct 1, 2024, 18:57 GMT+9

mentioned in commit 1402c615df16cc19846c49f969515f791de69df9

**Comment by Kguswo** [comment]
In GitLab by @Celinemad on Oct 2, 2024, 15:51 GMT+9

mentioned in commit 4af57c251935d7c1ec38f589bb58323fc820ecaf

**Comment by Kguswo** [comment]
In GitLab by @Celinemad on Oct 3, 2024, 15:20 GMT+9

mentioned in commit 9140c93c6a4c7bde8eb74f31aa1852cec8981dd8

**Comment by Kguswo** [comment]
In GitLab by @Celinemad on Oct 3, 2024, 19:11 GMT+9

mentioned in commit 40230dd7d1f4174c362239066d6e88d2df17edca

**Comment by Kguswo** [comment]
In GitLab by @Celinemad on Oct 3, 2024, 19:12 GMT+9

mentioned in commit cd8c7ddb3f985328f25bbac983c0d1df0e52b441

**Comment by Kguswo** [comment]
In GitLab by @Celinemad on Oct 3, 2024, 19:19 GMT+9

mentioned in commit e4b34d261bc482506afaf26d71f405a8bdbb63e4

**Comment by Kguswo** [comment]
In GitLab by @Celinemad on Oct 3, 2024, 19:26 GMT+9

mentioned in commit a928fad96c1eb9874d8f3abcf161a3aec4a1d253

**Comment by Kguswo** [comment]
In GitLab by @Celinemad on Oct 4, 2024, 09:51 GMT+9

mentioned in commit 34352061852e9d4651647ddd830fd80635cef685

**Comment by Kguswo** [comment]
In GitLab by @Celinemad on Oct 4, 2024, 10:31 GMT+9

mentioned in commit b207d8a108b8763ae87d75b2af1bbf8f648a0dac

**Comment by Kguswo** [comment]
In GitLab by @Celinemad on Oct 4, 2024, 17:44 GMT+9

mentioned in commit 2ff60aba4d4b125658ad1b6b1695cbf45aff8f50

**Comment by Kguswo** [comment]
In GitLab by @Celinemad on Oct 4, 2024, 17:44 GMT+9

mentioned in commit a963210ad77978d9053794530d49be0b196c2fc0

**Comment by Kguswo** [comment]
In GitLab by @Celinemad on Oct 4, 2024, 17:53 GMT+9

mentioned in commit 1a8de592e5ce2d4e068a4b7ba8d7d6f9f342d7be

**Comment by Kguswo** [comment]
In GitLab by @Celinemad on Oct 5, 2024, 15:53 GMT+9

mentioned in commit 39b2009f5e89b9eebb970b8a79cf634cf5165613

**Comment by Kguswo** [comment]
In GitLab by @Celinemad on Oct 5, 2024, 17:39 GMT+9

marked the checklist item **대출 변동사항 수정** as completed
