### ISSUE TITLE
[Feat #119] 미니게임 돈줍기 - [merged]

### ISSUE THREAD

**Issue by Kguswo** [Kguswo/OMG#368]
_Merges feature/back/money-pickup -> develop_

## 주요 변경사항
- 주울 돈 좌표 일단 임의로 (1, 1, 1) ~ (10, 10, 10)을 각각 point1~point10으로 매칭해두었습니다. 차후 수정해야합니다
- 맵에 랜덤 5곳에 두 종류의 돈이 랜덤으로 생성됩니다.
- 플레이어가 돈에 근접하여 스페이스바로 줍기행동을 실행하였을때 이후의 로직을 작성하였습니다

- 랜덤돈 배열 
```json
"moneyPoints": [
            [   {
                    "moneyCoordinates": [9,9,9],
                    "moneyStatus": 1
                },
                {
                    "moneyCoordinates": [6,6,6],
                    "moneyStatus": 2
                },
                {
                    "moneyCoordinates": [8,8,8],
                    "moneyStatus": 1
                },
                {
                    "moneyCoordinates": [3,3,3],
                    "moneyStatus": 2
                },
                {
                    "moneyCoordinates": [1,1,1],
                    "moneyStatus": 1
                }
            ]
        ]
```
이렇게 생성된다고 보시면 되고
얼마 짜린지 여부에 따라 먹었을 때 2면 5$ , 1이면 1$ 로 임의 구현해놓았습니다.
- 나머지는 API명세서 참고해주세요

## Todo
- [x] 돈 생성할 좌표 변경
- [x] 먹은 돈 처리 및 응답
- [x] 개인판 수정 및 응답
- [x] API 명세서 작성

## 리뷰 요청 사항
- [x] 돈 생성할 좌표 정하고 변경
- [ ] 돈 가치 금/은 얼마로 할지 정하고 변경
- [x] Changes에 Review로 언급해놓았으니 코드로 봐도됩니다
- [ ] **이 브랜치에서 쭉 작업할게요 지우지마세요! 확인하고 체크하신 뒤 승인 및 병합만 부탁드립니다👍**__

Closes #119

*Migrated from GitLab: https://lab.ssafy.com/s11-fintech-finance-sub1/S11P21A206/-/merge_requests/237*

**Comment by Kguswo** [comment]
requested review from @ssenna3

**Comment by Kguswo** [comment]
requested review from @hyun3745 and removed review request for @ssenna3

**Comment by Kguswo** [comment]
requested review from @ssenna3 and removed review request for @hyun3745

**Comment by Kguswo** [comment]
added 8 commits

<ul><li>597af87a...13cb4627 - 6 commits from branch <code>develop</code></li><li>7891825d - Merge branch &#39;develop&#39; of...</li><li>cf0501ce - [#119] Feat: Update Money Pickup</li></ul>

[Compare with previous version](/s11-fintech-finance-sub1/S11P21A206/-/merge_requests/237/diffs?diff_id=1394895&start_sha=597af87a220d825f1d1ca5e1b91c59fa6a2195cd)

**Comment by Kguswo** [comment]
added 2 commits

<ul><li>795793ce - [#121] Feat: Update Claude Chatbot</li><li>3be532cc - [#121] Feat: Update Claude Chatbot</li></ul>

[Compare with previous version](/s11-fintech-finance-sub1/S11P21A206/-/merge_requests/237/diffs?diff_id=1394899&start_sha=cf0501ce7ea17e46fd687fffde1c07252b91cb52)

**Comment by Kguswo** [comment]
added 1 commit

<ul><li>e15f59b2 - [#121] Feat: Update Claude Chatbot</li></ul>

[Compare with previous version](/s11-fintech-finance-sub1/S11P21A206/-/merge_requests/237/diffs?diff_id=1394900&start_sha=3be532cc7c01882b788697980b0980b0b57a8e16)

**Comment by Kguswo** [comment]
added 1 commit

<ul><li>c8563a5c - [#121] Feat: Update Prompt</li></ul>

[Compare with previous version](/s11-fintech-finance-sub1/S11P21A206/-/merge_requests/237/diffs?diff_id=1394904&start_sha=e15f59b2cf9cdfb1fb394c86f3c1451ef0656d8f)

**Comment by Kguswo** [comment]
added 1 commit

<ul><li>c09e1e0e - [#119] Feat: Update moneyPickup</li></ul>

[Compare with previous version](/s11-fintech-finance-sub1/S11P21A206/-/merge_requests/237/diffs?diff_id=1395048&start_sha=c8563a5c11f695baa29cd69418369e0cb94728a5)

**Comment by Kguswo** [comment]
added 1 commit

<ul><li>3e49ca30 - [#119] Fix : fix collectMoney</li></ul>

[Compare with previous version](/s11-fintech-finance-sub1/S11P21A206/-/merge_requests/237/diffs?diff_id=1395196&start_sha=c09e1e0ef67630b8d9d3fe3e5a0f43b33c4c0ec0)

**Comment by Kguswo** [comment]
In GitLab by @ssenna3 on Oct 14, 2024, 21:49 GMT+9

marked the checklist item **돈 생성할 좌표 정하고 변경** as completed

**Comment by Kguswo** [comment]
In GitLab by @ssenna3 on Oct 14, 2024, 21:49 GMT+9

marked the checklist item **돈 생성할 좌표 정하고 변경** as incomplete

**Comment by Kguswo** [comment]
In GitLab by @ssenna3 on Oct 14, 2024, 21:49 GMT+9

marked the checklist item **돈 생성할 좌표 정하고 변경** as completed

**Comment by Kguswo** [comment]
In GitLab by @ssenna3 on Oct 14, 2024, 21:49 GMT+9

marked the checklist item **돈 가치 금/은 얼마로 할지 정하고 변경** as completed

**Comment by Kguswo** [comment]
In GitLab by @ssenna3 on Oct 14, 2024, 21:49 GMT+9

marked the checklist item **돈 가치 금/은 얼마로 할지 정하고 변경** as incomplete

**Comment by Kguswo** [comment]
In GitLab by @ssenna3 on Oct 14, 2024, 21:49 GMT+9

marked the checklist item **Changes에 Review로 언급해놓았으니 코드로 봐도됩니다** as completed

**Comment by Kguswo** [comment]
In GitLab by @ssenna3 on Oct 14, 2024, 21:49 GMT+9

approved this merge request

**Comment by Kguswo** [comment]
In GitLab by @ssenna3 on Oct 14, 2024, 21:50 GMT+9

mentioned in commit e234c3a7f0e01ca41a1f5e35821fafe48dff5af4
