### ISSUE TITLE
경제 이벤트 로직 수정

### ISSUE THREAD

**Issue by Kguswo** [Kguswo/OMG#49]
### Issue
- 경제 이벤트의 내용을 크리스마스 컨셉에 맞게 수정
- 경제 이벤트를 보고 전략적으로 게임하도록 반영 라운드를 변경
- 경제 이벤트가 금리 뿐만 아니라 주식 가격에도 영향을 주도록 추가

### Todo
- [x] 경제 이벤트 컨셉 및 내용 변경, 주식 산업별로 구분
- [x] 경제 이벤트 data table 생성 및 값 수정
- [x] 경제 이벤트 반영 라운드를 변경
- [x] 경제 이벤트 반영 범위를 금리 + 주가로 변경
- [x] API 명세서 수정

추가할 사항이나 궁금한 점 comment 남겨주세요.

*Migrated from GitLab: https://lab.ssafy.com/s11-fintech-finance-sub1/S11P21A206/-/issues/49*

**Comment by Kguswo** [comment]
marked the checklist item **경제 이벤트 컨셉 및 내용 변경, 주식 산업별로 구분** as completed

**Comment by Kguswo** [comment]
marked the checklist item **경제 이벤트 data table 생성 및 값 수정** as completed

**Comment by Kguswo** [comment]
marked the checklist item **경제 이벤트 반영 라운드를 변경** as completed

**Comment by Kguswo** [comment]
marked the checklist item **경제 이벤트 반영 범위를 금리 + 주가로 변경** as completed

**Comment by Kguswo** [comment]
mentioned in commit 8562e883b7bd3c240681574784f4898858cc0a79

**Comment by Kguswo** [comment]
mentioned in commit c18b7bfc660185a0ece242acc67f9c98e496a74e

**Comment by Kguswo** [comment]
mentioned in commit 61411aec0d42a1e38f77e05940fa7e94baebea5e

**Comment by Kguswo** [comment]
mentioned in commit 1bb4c67c5f11aef5c4159fc71f1a6c89696c0ef2

**Comment by Kguswo** [comment]
marked the checklist item **API 명세서 수정** as completed

**Comment by Kguswo** [comment]
mentioned in commit aadf22b1789ae80e0252451f3030cb4fa7927c99

**Comment by Kguswo** [comment]
mentioned in commit 11d28810a227d984569a1427093ba31dff816687

**Comment by Kguswo** [comment]
mentioned in commit d49e66ff582e70784e26251f04e1d095ff9411f0

**Comment by Kguswo** [comment]
mentioned in commit a57c766e54913ae7dbe422301ab01c82e45da4db

**Comment by Kguswo** [comment]
mentioned in commit fdac1943dd98181bdc7a7c569b597549ea2affb2
