### ISSUE TITLE
[Feat] 게임 시작 이후 : 렌더링 체크 및 게임 초기화, 게임 이벤트 로직

### ISSUE THREAD

**Issue by Kguswo** [Kguswo/OMG#9]
## Issue
- 경제 이벤트 리스트 정하고 어떻게 변화 시킬지 미리 작성

## ToDo List
- [x] 플레이어별 렌더링 실시간 체크
- [x] 렌더링 완료 여부에 따른 게임 시작 및 초기화
- [x] 2라운드 이후 게임 이벤트에 따른 금리 변화 적용

*Migrated from GitLab: https://lab.ssafy.com/s11-fintech-finance-sub1/S11P21A206/-/issues/9*

**Comment by Kguswo** [comment]
mentioned in commit dc960d54e084f34c5d06547ba9c5f0210a288201

**Comment by Kguswo** [comment]
mentioned in commit 48bb190dc7b167f3fda089452760d89ddf19b59f

**Comment by Kguswo** [comment]
mentioned in commit c8fda3a651e319917d62c302b7865ea102d2fd4d

**Comment by Kguswo** [comment]
mentioned in commit 5595bc6a49e6c9e1bf8db2198fe1bac39bedbe50

**Comment by Kguswo** [comment]
mentioned in commit 980b424f26179df339613bb3b7403f934e4d0e8d

**Comment by Kguswo** [comment]
mentioned in commit a50f6768d7355a689ab7da7098401e19473a4038

**Comment by Kguswo** [comment]
mentioned in commit 957d787a4a3625eaaa32eed9acf58cc3f3160552

**Comment by Kguswo** [comment]
mentioned in commit 4c4f593625b42076e7254affed930fab0f96603a

**Comment by Kguswo** [comment]
mentioned in commit c4839d47a66d8da0cb4c44f46bffd205050bfe48

**Comment by Kguswo** [comment]
mentioned in commit f7b5d1daf484be2ff6a60063113b2c3d4121764f

**Comment by Kguswo** [comment]
mentioned in commit 37e14f9fa0b8a9bad19fcf180136e0be0f40dbd4

**Comment by Kguswo** [comment]
mentioned in commit 8e8c809a2b23b29ff4cdd5b527d32ed4e5c7c2a7

**Comment by Kguswo** [comment]
marked the checklist item **플레이어별 렌더링 실시간 체크** as completed

**Comment by Kguswo** [comment]
mentioned in commit 17a28b366cb97dd93b1e4d5b26376406381457aa

**Comment by Kguswo** [comment]
mentioned in commit 61e94d88efdab2fcc3edefc54411b184ac9cdd50

**Comment by Kguswo** [comment]
mentioned in commit d969ebc99431e3285fbb165f18f80e7ab8365283

**Comment by Kguswo** [comment]
marked the checklist item **렌더링 완료 여부에 따른 게임 시작 및 초기화** as completed

**Comment by Kguswo** [comment]
marked the checklist item **2라운드 이후 게임 이벤트에 따른 금리 변화 적용** as completed

**Comment by Kguswo** [comment]
mentioned in commit 37d8da852fbf908fb0d862d4b76ff8e54654b1ae

**Comment by Kguswo** [comment]
mentioned in commit 5e02fb07d654ebbee20af93bf6531a8ee86e5040

**Comment by Kguswo** [comment]
mentioned in commit 3df860fd532e9e76833084a8d60ee84274a50c2e

**Comment by Kguswo** [comment]
mentioned in commit 67ca238296ed79f9ddf48464507cbaa29637e62b
